Adapt echo bot to match slurk v3
clp-research/slurk-bots pull request #17
Opened 2021-07-21 20:46 UTC by wencke-lm

Replaces #12 

r? @TimDiekmann in case you want to verify
r? @janagoetze

2021-07-21 23:24 UTC, TimDiekmann requested changes

2021-07-21 23:24 UTC, TimDiekmann commented on echo/README.md
> +The token needs to have atleast the permissions `send_privately` and `send_message`. Please refer to <https://clp-research.github.io/slurk/slurk_multibots.html> for more detailed information.
cc clp-research/slurk#153

2021-07-21 23:24 UTC, TimDiekmann commented on echo/echo.py
> +        LOG.info(f"Running concierge bot on {self.uri} with token {self.token}")
```suggestion
        LOG.info(f"Running echo bot on {self.uri} with token {self.token}")
```

2021-07-21 23:24 UTC, TimDiekmann commented on echo/echo.py
> +    def message_callback(success, error_msg=None):
```suggestion
    def message_callback(success, error_msg="Unknown Error"):
```

2021-07-21 23:24 UTC, TimDiekmann commented on echo/echo.py
> +                    exit(2)
```suggestion
                    response.raise_for_status()
```

2021-07-21 23:24 UTC, TimDiekmann commented on echo/README.md
> +The token needs to have atleast the permissions `send_privately` and `send_message`. Please refer to <https://clp-research.github.io/slurk/slurk_multibots.html> for more detailed information.
It also needs `api` as it attempts to join a room.

2021-07-21 23:24 UTC, TimDiekmann commented on echo/echo.py
> +    port = {"default": os.environ.get("SLURK_PORT")}
```suggestion
    port = {"default": os.environ.get("SLURK_PORT", "80")}
```

2021-07-21 23:24 UTC, TimDiekmann commented on echo/echo.py
> +        self.uri += "/slurk/api"
When applying the suggestion below, the port is guaranteed to be set:
```suggestion
        self.uri = f"{host}:{port}/slurk/api"
```

2021-07-21 23:24 UTC, TimDiekmann commented on echo/echo.py
> +        "-t", "--token", help="token for logging in as bot (see SERVURL/token)", **token
This was a long time ago 🤣 
```suggestion
        "-t", "--token", help="token for logging in as bot", **token
```

2021-07-23 15:37 UTC, wencke-lm commented on echo/README.md
> +The token needs to have atleast the permissions `send_privately` and `send_message`. Please refer to <https://clp-research.github.io/slurk/slurk_multibots.html> for more detailed information.
Yes, correct. And we also need `send_image`.

2021-07-23 18:26 UTC, TimDiekmann approved these changes

2021-07-23 18:26 UTC, TimDiekmann commented on echo/README.md
> +The token needs to have atleast the permissions `api`, `send_privately`, `send_message` and `send_image`. Please refer to <https://clp-research.github.io/slurk/slurk_multibots.html> for more detailed
```suggestion
The token needs to have at least the permissions `api`, `send_privately`, `send_message`, and `send_image`. Please refer to <https://clp-research.github.io/slurk/slurk_multibots.html> for more detailed information.
```

2021-07-23 18:29 UTC, TimDiekmann commented on echo/echo.py
> +    port = {"default": os.environ.get("SLURK_PORT", "80")}
I had to rethink this, for "https://" addresses, this won't work, as this would default to 443. Sorry...
Either this needs to be reverted, or `host` has to be checked for "https". The former is probably more clear and less error prone.

2021-07-25 15:05 UTC, wencke-lm commented on echo/echo.py
> +                response = requests.post(
Authentification Header missing.

2021-08-02 12:52 UTC, merged